# Generated by Django 3.1 on 2020-08-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('state', models.CharField(blank=True, max_length=200, null=True, verbose_name='State')),
                ('country', models.CharField(max_length=2, verbose_name='Country')),
                ('lat', models.CharField(max_length=30, verbose_name='Latitude')),
                ('lon', models.CharField(max_length=30, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['country', 'name'],
                'unique_together': {('name', 'state', 'country')},
            },
        ),
    ]
